name: Deploy

on:
  push:
    branches: ["main", "dev", "Backend_development"]
  pull_request:
    branches: ["main", "dev", "Backend_development"]

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "adopt"

      - name: Authorize running gradlew
        run: chmod +x gradlew
        working-directory: ./backend/alfa

      - name: Unit tests and build artifact
        run: ./gradlew build
        working-directory: ./backend/alfa

      - name: Rename artifact
        run: cp build/libs/Warhammer-0.0.1-SNAPSHOT.jar Warhammer-${{ github.sha }}.jar
        working-directory: ./backend/alfa

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: Warhammer
          path: ./backend/alfa/Warhammer-${{ github.sha }}.jar
  deploy:
    runs-on: self-hosted
    needs: run-unit-tests
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: Warhammer

      - name: Deploy
        run: ls Warhammer*.jar
#aws s3 cp build/libs/Warhammer-0.0.1-SNAPSHOT.jar s3://warhammer-backend-bucket/Warhammer-0.0.1-SNAPSHOT.jar
#aws ec2 run-instances --image-id WarhammerBackendImage --count 1 --instance-type t2.micro --key-name Warhammer-ssh-key --subnet-id Warhammer-vpc --security-group WarhammerSecurityGroup --user-data file://startup.sh --associate-public-ip-address
